print("Первый этап развития")
a1=input ()
print("Второй этап развития")
a2=input ()
print("Третий этап развития")
a3=input ()
print("Четвертый этап развития")
a4=input ()
print("Пятый этап развития")
a5=input ()
print(a1,a2,a3,a4,a5, sep='=>')
